server:
  port: 8085

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-ui

camunda.bpm.client:
  base-url: http://localhost:8090/engine-rest/
  lock-duration: 1

feign:
  client:
    config:
      processDefinition:
        url: http://localhost:8090/engine-rest/
      historicProcessInstance:
        url: http://localhost:8090/engine-rest/
      historicVariableInstanceClient:
        url: http://localhost:8090/engine-rest/
      camundaProcessDefinitionApi:
        url: http://localhost:8090/engine-rest/